name: CI
on:
  push:
    branches:
      - ci-change-detection

jobs:
  change_detection:
    strategy:
      matrix:
        pipelines: [la_edu, 3D_windowing_edu]
    runs-on: ubuntu-latest
    name: change-d
    steps:
      - uses: actions/checkout@v2
      - id: change-detection
        uses: ./.github/actions/pipeline-change-detection
        with:
          piplines-to-check: ${{ matrix.pipelines }}
      - run: echo ${{ steps.change-d.outputs.changed }}
        shell: bash