name: CI
on:
  push:
    branches:
      - ci-change-detection

jobs:
  change_detection:
    strategy:
      matrix:
        pipelines: [la_edu, 3D_windowing_edu]
    runs-on: ubuntu-latest
    name: change-d
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '2'
      - id: change-detection
        uses: ./.github/actions/pipeline-change-detection
        with:
          pipline-to-check: ${{ matrix.pipelines }}
      - run: echo ${{ steps.change-detection.outputs.changed }}
        shell: bash
  ci:
    strategy:
      fail-fast: false
      matrix:
        python-version: [ 3.9 ]
        poetry-version: [ 1.1.11 ]
        pipelines: [ la_edu ]
        os: [ ubuntu-18.04, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Setup Tox
        run: |
          python -m pip install --upgrade pip
          pip install tox tox-gh-actions
      - name: Test with tox
        run: tox -c ${{ matrix.pipelines }}