name: CI
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        python-version: [ 3.9 ]
        poetry-version: [ 1.1.11 ]
        pipelines: [ la_edu, 3D_windowing_edu ]
        os: [ ubuntu-18.04, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - id: change-detection
        uses: ./.github/actions/pipeline-change-detection
        with:
          pipline-to-check: ${{ matrix.pipelines }}
      - run: echo ${{ steps.change-detection.outputs.changed }}
        shell: bash
      - name: Setup Python
        if: ${{ steps.change-detection.outputs.changed == 'true' }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Setup Tox
        if: ${{ steps.change-detection.outputs.changed == 'true' }}
        run: |
          python -m pip install --upgrade pip
          pip install tox tox-gh-actions
      - name: Test with tox
        if: ${{ steps.change-detection.outputs.changed == 'true' }}
        run: tox -c ${{ matrix.pipelines }}